#!/usr/bin/with-contenv bash

if [[ ! -z "$HC_PING_ID" && ! -f "/scripts/pre-backup.sh" && ! -f "/scripts/post-backup.sh" ]]; then
  echo curl -fsS -m 10 --retry 5 -o /dev/null "https://hc-ping.com/$HC_PING_ID/start" \
       > /scripts/pre-backup.sh
  echo curl -fsS -m 10 --retry 5 --data-binary @/tmp/backup.log "https://hc-ping.com/$HC_PING_ID/\$1" \
       > /scripts/post-backup.sh
fi
